package com.rocinante.combat;

import com.rocinante.state.AttackStyle;
import com.rocinante.state.GroundItemSnapshot;
import lombok.Builder;
import lombok.Value;

/**
 * Represents a queued combat action to be executed.
 *
 * Actions are generated by CombatManager checks and executed in priority order.
 */
@Value
@Builder
public class CombatAction {

    /**
     * Types of combat actions.
     */
    public enum Type {
        /**
         * Eat food from inventory.
         */
        EAT,

        /**
         * Switch protection prayer.
         */
        PRAYER_SWITCH,

        /**
         * Use special attack.
         */
        SPECIAL_ATTACK,

        /**
         * Retarget an NPC.
         */
        RETARGET,

        /**
         * Pick up ground item.
         */
        LOOT,

        /**
         * Switch gear/equipment.
         */
        GEAR_SWITCH,

        /**
         * Flee from combat (teleport/run).
         */
        FLEE,

        /**
         * Drink a potion (prayer restore, antipoison, etc.).
         */
        DRINK_POTION
    }

    /**
     * Priority levels for action execution.
     */
    public enum Priority {
        /**
         * Execute immediately, interrupt current actions.
         */
        URGENT(0),

        /**
         * High priority, execute soon.
         */
        HIGH(1),

        /**
         * Normal priority.
         */
        NORMAL(2),

        /**
         * Low priority, execute when convenient.
         */
        LOW(3);

        private final int value;

        Priority(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }
    }

    /**
     * The type of action.
     */
    Type type;

    /**
     * Action priority.
     */
    @Builder.Default
    Priority priority = Priority.NORMAL;

    /**
     * Primary inventory slot (for eating, potions).
     */
    @Builder.Default
    int primarySlot = -1;

    /**
     * Secondary slot (for combo eating with karambwan).
     */
    @Builder.Default
    int secondarySlot = -1;

    /**
     * Whether this is a combo eat action.
     */
    @Builder.Default
    boolean comboEat = false;

    /**
     * Attack style for prayer switching.
     */
    @Builder.Default
    AttackStyle attackStyle = AttackStyle.UNKNOWN;

    /**
     * Target NPC index for retargeting.
     */
    @Builder.Default
    int targetNpcIndex = -1;

    /**
     * Ground item for looting.
     */
    GroundItemSnapshot groundItem;

    /**
     * Gear set name for gear switching.
     */
    String gearSetName;

    /**
     * Teleport item/spell for fleeing.
     */
    String fleeMethod;

    /**
     * Potion item ID for drinking.
     */
    @Builder.Default
    int potionId = -1;

    /**
     * Item ID of consumed item (for tracking brews/restores/food).
     */
    @Builder.Default
    int itemId = -1;

    // ========================================================================
    // Convenience Methods
    // ========================================================================

    /**
     * Check if this action is higher priority than another.
     *
     * @param other the other action
     * @return true if this is higher priority (lower value)
     */
    public boolean isHigherPriorityThan(CombatAction other) {
        if (other == null) {
            return true;
        }
        return priority.getValue() < other.priority.getValue();
    }

    /**
     * Check if this action is urgent.
     *
     * @return true if urgent priority
     */
    public boolean isUrgent() {
        return priority == Priority.URGENT;
    }

    /**
     * Get a description of this action.
     *
     * @return human-readable description
     */
    public String getDescription() {
        switch (type) {
            case EAT:
                return comboEat ? "Combo eat" : "Eat food";
            case PRAYER_SWITCH:
                return "Switch to " + attackStyle + " protection";
            case SPECIAL_ATTACK:
                return "Use special attack";
            case RETARGET:
                return "Retarget NPC";
            case LOOT:
                return groundItem != null ? "Loot " + groundItem.getName() : "Loot item";
            case GEAR_SWITCH:
                return "Switch to " + (gearSetName != null ? gearSetName : "gear");
            case FLEE:
                return "Flee via " + (fleeMethod != null ? fleeMethod : "escape");
            case DRINK_POTION:
                return "Drink potion";
            default:
                return type.toString();
        }
    }
}

